- hosts: all
  become: true

  vars:
    server_type: guest
    telegraf_agent_version: 1.19.2-yn
    telegraf_agent_version_patch: be742cbf
    telegraf_agent_disable_version: (yn-release-1\.5)|(v1\.5\.0~5d6622e)|(v1\.5\.0~yn)
    telegraf_agent_interval: 60
    telegraf_agent_flush_interval: 60
    telegraf_agent_omit_hostname: True
    telegraf_agent_output:
      - type: influxdb
        config:
          - urls = ["{{ influxdb_url }}"]
          - database = "{{ influxdb_name }}"
          - insecure_skip_verify = true

  tasks:
    - name: "Deploy monitor agent for Guest"
      include_role:
        name: ansible-telegraf
      vars:
        telegraf_plugins_default:
          - plugin: cpu
            config:
              - name_prefix = "agent_"
              - percpu = true
              - totalcpu = true
              - collect_cpu_time = false
              - report_active = true
          - plugin: disk
            config:
              - name_prefix = "agent_"
              - ignore_fs = ["tmpfs", "devtmpfs", "overlay", "squashfs", "iso9660"]
          - plugin: diskio
            config:
              - name_prefix = "agent_"
              - skip_serial_number = false
          - plugin: kernel
            config:
              - name_prefix = "agent_"
          - plugin: kernel_vmstat
            config:
              - name_prefix = "agent_"
          - plugin: mem
            config:
              - name_prefix = "agent_"
          - plugin: processes
            config:
              - name_prefix = "agent_"
          - plugin: swap
            config:
              - name_prefix = "agent_"
          - plugin: system
            config:
              - name_prefix = "agent_"
          - plugin: net
            config:
              - name_prefix = "agent_"
          - plugin: netstat
            config:
              - name_prefix = "agent_"
          - plugin: nstat
            config:
              - name_prefix = "agent_"
          - plugin: internal
            config:
              - name_prefix = "agent_"
              - collect_memstats = false
      when: 
        - server_type == "guest"
        - ansible_facts['os_family'] != "Windows"

    - name: "Deploy monitor agent for Windows Guest"
      include_role:
        name: ansible-telegraf
      vars:
        telegraf_plugins_default:
          - plugin: cpu
            config:
              - name_prefix = "agent_"
              - percpu = true
              - totalcpu = true
              - collect_cpu_time = false
              - report_active = true
          - plugin: disk
            config:
              - name_prefix = "agent_"
              - ignore_fs = ["tmpfs", "devtmpfs", "overlay", "squashfs", "iso9660"]
          - plugin: diskio
            config:
              - name_prefix = "agent_"
              - skip_serial_number = false
          - plugin: mem
            config:
              - name_prefix = "agent_"
          - plugin: processes
            config:
              - name_prefix = "agent_"
          - plugin: system
            config:
              - name_prefix = "agent_"
          - plugin: net
            config:
              - name_prefix = "agent_"
          - plugin: netstat
            config:
              - name_prefix = "agent_"
          - plugin: nstat
            config:
              - name_prefix = "agent_"
          - plugin: internal
            config:
              - name_prefix = "agent_"
              - collect_memstats = false
      when: 
        - server_type == "guest"
        -  ansible_facts['os_family'] == "Windows"

    - block:
      - name: "Install lm-sensors for Baremetal"
        include_role:
          name: lm-sensors

      - name: "Install smartmontools and nvme-cli for Baremetal"
        include_role:
          name: smartmontools
      ignore_errors: yes
      when: server_type == "baremetal"

    - name: "Deploy monitor agent for Baremetal"
      include_role:
        name: ansible-telegraf
      vars:
        telegraf_plugins_default:
          - plugin: cpu
            config:
              - name_prefix = "agent_"
              - percpu = true
              - totalcpu = true
              - collect_cpu_time = false
              - report_active = true
          - plugin: disk
            config:
              - name_prefix = "agent_"
              - ignore_fs = ["tmpfs", "devtmpfs", "overlay", "squashfs", "iso9660"]
          - plugin: diskio
            config:
              - name_prefix = "agent_"
              - skip_serial_number = false
          - plugin: sensors
            config:
              - name_prefix = "agent_"
          - plugin: smart
            config:
              - name_prefix = "agent_"
              - use_sudo = true
          - plugin: kernel
            config:
              - name_prefix = "agent_"
          - plugin: kernel_vmstat
            config:
              - name_prefix = "agent_"
          - plugin: mem
            config:
              - name_prefix = "agent_"
          - plugin: processes
            config:
              - name_prefix = "agent_"
          - plugin: swap
            config:
              - name_prefix = "agent_"
          - plugin: system
            config:
              - name_prefix = "agent_"
          - plugin: net
            config:
              - name_prefix = "agent_"
          - plugin: netstat
            config:
              - name_prefix = "agent_"
          - plugin: nstat
            config:
              - name_prefix = "agent_"
          - plugin: internal
            config:
              - name_prefix = "agent_"
              - collect_memstats = false
      when: server_type == "baremetal"

